# Generated by Django 3.2 on 2023-03-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_order_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='product_color',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
