# Generated by Django 3.2 on 2023-01-11 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20230111_1209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image_2',
            new_name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_main',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_url_2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_url_3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_url_4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_url_main',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
