# Generated by Django 3.2 on 2023-01-11 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20230111_1625'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
