# Generated by Django 3.2 on 2023-01-11 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_delete_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
