# Generated by Django 3.2 on 2023-01-11 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20230111_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url_2',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image_url_3',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
