# Generated by Django 3.2 on 2023-01-23 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20230111_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color_choice',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
